# Tests that there is a deployment named coredns with all replicas available
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
status:
  readyReplicas: 2
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-proxy
  namespace: kube-system
spec:
  template:
    spec:
      # the `~` modifier tells Chainsaw to iterate over the array elements
      ~.(containers):
        securityContext:
          privileged: true
